# Generated by Django 2.0.9 on 2018-12-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('wiki', models.TextField(null=True)),
                ('release_note', models.TextField(null=True)),
                ('fastboot', models.TextField()),
                ('qfil', models.TextField()),
                ('status', models.TextField()),
                ('description', models.TextField(null=True)),
                ('release_date', models.TextField(null=True)),
                ('apps_id', models.TextField(null=True)),
                ('au_tag', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('category', models.TextField()),
                ('wiki', models.TextField(null=True)),
                ('description', models.TextField()),
                ('project_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='sp_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.SP'),
        ),
    ]
