# Generated by Django 2.0.9 on 2018-12-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sp',
            options={'managed': False},
        ),
    ]
