# Generated by Django 2.0.9 on 2018-12-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20181206_0221'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='build',
            table='build',
        ),
        migrations.AlterModelTable(
            name='sp',
            table='sp',
        ),
    ]
