# Generated by Django 2.0.9 on 2018-12-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181206_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'managed': True},
        ),
    ]
